export const games = [
  {
    name: "2048",
    slug: "2048",
    localFile: "/games/sausi/puzzle/2048/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["merge", "numbers", "classic"],
    description: "Slide tiles. Merge matching numbers. Reach 2048.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/2048.png",
  },
  {
    name: "6 Octagons",
    slug: "6oct",
    localFile: "/games/sausi/puzzle/6oct/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["tiles", "minimal"],
    description: "Octagon-tile sliding puzzle.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/6 Octagons.png",
  },
  {
    name: "Rock Paper Scissors",
    slug: "rock-paper-scissors",
    localFile: "/games/sausi/board/rock-paper-scissors/index.html",
    cats: ["board"],
    category: "board",
    tech: "phaser",
    tags: ["classic", "quick"],
    description: "The timeless hand game vs the AI.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Rock Paper Scissors.png",
  },
  {
    name: "Sudoku",
    slug: "sudoku",
    localFile: "/games/sausi/puzzle/sudoku/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "html",
    tags: ["logic", "numbers", "classic"],
    description: "Classic 9x9 number logic puzzle.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Sudoku.png",
  },
  {
    name: "Abhita",
    slug: "abhita",
    localFile: "/games/sausi/arcade/abhita/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["reflex", "dodge"],
    description: "Reflex-driven dodge mini-game.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Abhita.png",
  },
  {
    name: "Alien Battle",
    slug: "alien-battle",
    localFile: "/games/sausi/shooter/alien-battle/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["aliens", "top-down", "survival"],
    description: "Top-down alien shooter. Survive the swarm.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Alien Battle.png",
  },
  {
    name: "Anti-Gravity",
    slug: "antigravity",
    localFile: "/games/sausi/platformer/antigravity/index.html",
    cats: ["platformer"],
    category: "platformer",
    tech: "phaser",
    tags: ["physics", "gravity"],
    description: "Flip gravity to navigate hazards.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Anti-Gravity.png",
  },
  {
    name: "Archer",
    slug: "archer",
    localFile: "/games/sausi/sports/archer/index.html",
    cats: ["sports"],
    category: "sports",
    tech: "html",
    tags: ["bow", "aim", "precision"],
    description: "Aim, draw, and release. Hit your target.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Archer.png",
  },
  {
    name: "Balance Stack",
    slug: "balance-stack",
    localFile: "/games/sausi/arcade/balance-stack/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["stacking", "balance"],
    description: "Stack blocks without toppling the tower.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Balance Stack.png",
  },
  {
    name: "Basketball",
    slug: "basketball",
    localFile: "/games/sausi/sports/basketball/index.html",
    cats: ["sports"],
    category: "sports",
    tech: "phaser",
    tags: ["hoops", "arcade-sports"],
    description: "Arc the ball through the hoop.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Basketbal.png",
  },
  {
    name: "Bird Shooter",
    slug: "bird-shooter",
    localFile: "/games/sausi/shooter/bird-shooter/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["aim", "reflex"],
    description: "Track and shoot flying birds.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Bird Shooter.png",
  },
  {
    name: "Bomb Blast",
    slug: "bomb-blast",
    localFile: "/games/sausi/arcade/bomb-blast/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["explosions", "timing"],
    description: "Time the blast to chain destruction.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Bomb Blast.png",
  },
  {
    name: "Boom Dots",
    slug: "boom-dots",
    localFile: "/games/sausi/arcade/boom-dots/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["chain", "reflex"],
    description: "Tap to detonate dots and clear the screen.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Boom Dots.png",
  },
  {
    name: "Bowling",
    slug: "bowling",
    localFile: "/games/sausi/sports/bowling/index.html",
    cats: ["sports"],
    category: "sports",
    tech: "phaser",
    tags: ["pins", "aim", "sport"],
    description: "Knock down all the pins.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Bowling.png",
  },
  {
    name: "Breakoid",
    slug: "breakoid",
    localFile: "/games/sausi/arcade/breakoid/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["brick", "paddle", "classic"],
    description: "Breakout-style brick smashing.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Breakoid.png",
  },
  {
    name: "Bubble Pop",
    slug: "bubble-pop",
    localFile: "/games/sausi/casual/bubble-pop/index.html",
    cats: ["casual"],
    category: "casual",
    tech: "phaser",
    tags: ["match", "bubbles", "relaxing"],
    description: "Pop matching bubbles to score.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Bubble Pop.png",
  },
  {
    name: "Bubble Shooter",
    slug: "bubble-shooter",
    localFile: "/games/sausi/casual/bubble-shooter/index.html",
    cats: ["casual"],
    category: "casual",
    tech: "phaser",
    tags: ["match-3", "shooter", "classic"],
    description: "Shoot bubbles into matching color clusters.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Bubble Shooter.png",
  },
  {
    name: "Bug Smasher",
    slug: "bug-smasher",
    localFile: "/games/sausi/arcade/bug-smasher/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["whack", "reflex"],
    description: "Squash bugs before they reach the goal.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Bug Smasher.png",
  },
  {
    name: "Buttermilk",
    slug: "buttermilk",
    localFile: "/games/sausi/casual/buttermilk/index.html",
    cats: ["casual"],
    category: "casual",
    tech: "phaser",
    tags: ["idle", "pour", "cute"],
    description: "Cute pour-and-mix idle game.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Buttermilk.png",
  },
  {
    name: "Candy Crush",
    slug: "candy-crush",
    localFile: "/games/sausi/casual/candy-crush/index.html",
    cats: ["casual"],
    category: "casual",
    tech: "phaser",
    tags: ["match-3", "candy", "classic"],
    description: "Match-3 candy puzzle.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Candy Crush.png",
  },
  {
    name: "Candy Crusher",
    slug: "candy-crusher",
    localFile: "/games/sausi/casual/candy-crusher/index.html",
    cats: ["casual"],
    category: "casual",
    tech: "phaser",
    tags: ["match", "crush"],
    description: "Smash candy patterns for points.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Candy Crusher.png",
  },
  {
    name: "Cannon Blaster",
    slug: "cannon-blaster",
    localFile: "/games/sausi/shooter/cannon-blaster/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["cannon", "physics", "aim"],
    description: "Aim and fire cannonballs at targets.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Cannon Blaster.png",
  },
  {
    name: "Cargo Stack",
    slug: "cargo-stack",
    localFile: "/games/sausi/puzzle/cargo-stack/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["stacking", "logistics"],
    description: "Pack cargo crates without overflow.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Cargo Stack.png",
  },
  {
    name: "Car Race",
    slug: "car-race",
    localFile: "/games/sausi/racing/car-race/index.html",
    cats: ["racing"],
    category: "racing",
    tech: "three",
    tags: ["3d", "cars", "traffic"],
    description: "3D car-racing run with traffic dodging.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Car Race.png",
  },
  {
    name: "Carrom",
    slug: "carrom",
    localFile: "/games/sausi/board/carrom/index.html",
    cats: ["board"],
    category: "board",
    tech: "phaser",
    tags: ["table", "aim", "classic"],
    description: "Pocket the carrom pieces with skill.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Carrom.png",
  },
  {
    name: "Chess",
    slug: "chess",
    localFile: "/games/sausi/board/chess/index.html",
    cats: ["board"],
    category: "board",
    tech: "phaser",
    tags: ["strategy", "classic"],
    description: "Classic chess vs the computer.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Chess.png",
  },
  {
    name: "Circle Path",
    slug: "circle-path",
    localFile: "/games/sausi/arcade/circle-path/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["timing", "ring"],
    description: "Trace the rotating circle without slipping.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Circle Path.png",
  },
  {
    name: "Circuit Bulb",
    slug: "circuit-bulb",
    localFile: "/games/sausi/puzzle/circuit-bulb/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["logic", "wires"],
    description: "Wire circuits to light the bulb.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Circuit Bulb.png",
  },
  {
    name: "Catch Me If You Can",
    slug: "catch-me-if-you-can",
    localFile: "/games/sausi/arcade/catch-me-if-you-can/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["chase", "stealth"],
    description: "Outrun the chasers in a wide arena.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Catch Me If You Can.png",
  },
  {
    name: "Collector",
    slug: "collector",
    localFile: "/games/sausi/arcade/collector/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["coins", "time-attack"],
    description: "Sweep up coins before time runs out.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Collector.png",
  },
  {
    name: "Color Dash",
    slug: "color-dash",
    localFile: "/games/sausi/arcade/color-dash/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["color-match", "reflex"],
    description: "Match the player\u0027s color to pass each gate.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Color Dash.png",
  },
  {
    name: "Colour Pour",
    slug: "colour-pour",
    localFile: "/games/sausi/puzzle/colour-pour/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["sort", "liquid", "relax"],
    description: "Sort liquids into single-color tubes.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Colour Pour.png",
  },
  {
    name: "Connected",
    slug: "connected",
    localFile: "/games/sausi/puzzle/connected/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["graph", "logic"],
    description: "Link nodes without crossing lines.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Connected.png",
  },
  {
    name: "Cooking",
    slug: "cooking",
    localFile: "/games/sausi/casual/cooking/index.html",
    cats: ["casual"],
    category: "casual",
    tech: "phaser",
    tags: ["timer", "kitchen"],
    description: "Plate orders before the timer hits zero.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Cooking.png",
  },
  {
    name: "Cool Platformer",
    slug: "cool-platformer",
    localFile: "/games/sausi/platformer/cool-platformer/index.html",
    cats: ["platformer"],
    category: "platformer",
    tech: "phaser",
    tags: ["jump", "run", "platform"],
    description: "Run, jump, and dash through hazards.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Cool Platformer.png",
  },
  {
    name: "Cosmic Cleaner",
    slug: "cosmic-cleaner",
    localFile: "/games/sausi/3d/cosmic-cleaner/index.html",
    cats: ["3d"],
    category: "3d",
    tech: "phaser",
    tags: ["3d", "space"],
    description: "3D space-junk vacuum-up game.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Cosmic Cleaner.png",
  },
  {
    name: "Cricket 1-2-3",
    slug: "cricket-123",
    localFile: "/games/sausi/sports/cricket-123/index.html",
    cats: ["sports"],
    category: "sports",
    tech: "phaser",
    tags: ["cricket", "reflex"],
    description: "Bat through fast deliveries.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Cricket 1-2-3.png",
  },
  {
    name: "Crossy Road",
    slug: "crossy-road",
    localFile: "/games/sausi/arcade/crossy-road/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "three",
    tags: ["frogger", "endless"],
    description: "Hop across roads, rivers, and rails.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Crossy Road.png",
  },
  {
    name: "Crowd Control",
    slug: "crowd-control",
    localFile: "/games/sausi/arcade/crowd-control/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["growing", "io-style"],
    description: "Steer your growing crowd through obstacles.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Crowd Control.png",
  },
  {
    name: "Curve Snake",
    slug: "curve-snake",
    localFile: "/games/sausi/arcade/curve-snake/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "html",
    tags: ["snake", "trail"],
    description: "Snake-style game with smooth curve trails.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Curve Snake.png",
  },
  {
    name: "Cut the Rope",
    slug: "cut-rope",
    localFile: "/games/sausi/puzzle/cut-rope/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["physics", "slice"],
    description: "Slice ropes to land the candy in the goal.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Cut the Rope.png",
  },
  {
    name: "Demon",
    slug: "demon",
    localFile: "/games/sausi/arcade/demon/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["survival", "dark"],
    description: "Survive a horde of demonic enemies.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Demon.png",
  },
  {
    name: "Devil King",
    slug: "devil-king",
    localFile: "/games/sausi/platformer/devil-king/index.html",
    cats: ["platformer"],
    category: "platformer",
    tech: "phaser",
    tags: ["challenge", "jump"],
    description: "Hop hazards in a devilish trial run.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Devil King.png",
  },
  {
    name: "Dodge Enemy",
    slug: "dodge-enemy",
    localFile: "/games/sausi/arcade/dodge-enemy/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["dodge", "reflex"],
    description: "Slip past charging enemies.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Dodge Enemy.png",
  },
  {
    name: "Dodge Master",
    slug: "dodge-master",
    localFile: "/games/sausi/arcade/dodge-master/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["endless", "dodge"],
    description: "Endless dodging at increasing speed.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Dodge Master.png",
  },
  {
    name: "Doodle Jump",
    slug: "doodle-jump",
    localFile: "/games/sausi/platformer/doodle-jump/index.html",
    cats: ["platformer"],
    category: "platformer",
    tech: "phaser",
    tags: ["vertical", "jump", "classic"],
    description: "Jump from platform to platform — go higher.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Doodle Jump.png",
  },
  {
    name: "Dream Weaver",
    slug: "dream-weaver",
    localFile: "/games/sausi/arcade/dream-weaver/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["chill", "trail"],
    description: "Weave glowing trails through a dreamscape.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Dream Weaver.png",
  },
  {
    name: "Ellars",
    slug: "ellars",
    localFile: "/games/sausi/arcade/ellars/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["abstract", "dodge"],
    description: "Surreal arcade dodger.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Ellars.png",
  },
  {
    name: "Endless Mafia",
    slug: "endless-mafia",
    localFile: "/games/sausi/arcade/endless-mafia/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["brawler", "endless"],
    description: "Brawl through endless waves of mafia thugs.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Endless Mafia.png",
  },
  {
    name: "Endless Runner",
    slug: "endless-runner",
    localFile: "/games/sausi/racing/endless-runner/index.html",
    cats: ["racing"],
    category: "racing",
    tech: "phaser",
    tags: ["runner", "endless"],
    description: "Run forever. Dodge everything.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Endless Runner.png",
  },
  {
    name: "Fighter Fury",
    slug: "fighter-fury",
    localFile: "/games/sausi/shooter/fighter-fury/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["jet", "side-scroll"],
    description: "Side-scrolling jet shooter.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Fighter Fury.png",
  },
  {
    name: "Fighter Jet",
    slug: "fighter-jet",
    localFile: "/games/sausi/shooter/fighter-jet/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["jet", "top-down"],
    description: "Top-down jet combat.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Fighter Jet.png",
  },
  {
    name: "Flappy",
    slug: "flappy",
    localFile: "/games/sausi/arcade/flappy/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["tap", "one-button", "classic"],
    description: "Tap to flap. Don\u0027t hit the pipes.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Flappy.png",
  },
  {
    name: "Flip Jump",
    slug: "flip-jump",
    localFile: "/games/sausi/platformer/flip-jump/index.html",
    cats: ["platformer"],
    category: "platformer",
    tech: "phaser",
    tags: ["gravity", "flip"],
    description: "Flip the world to land safely.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Flip Jump.png",
  },
  {
    name: "Fly Monkey",
    slug: "fly-monkey",
    localFile: "/games/sausi/arcade/fly-monkey/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["swing", "jungle"],
    description: "Swing the monkey through the canopy.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Fly Monkey.png",
  },
  {
    name: "Football",
    slug: "football",
    localFile: "/games/sausi/sports/football/index.html",
    cats: ["sports"],
    category: "sports",
    tech: "html",
    tags: ["soccer", "goals"],
    description: "Score goals in a fast-paced footy match.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Football.png",
  },
  {
    name: "Forest Runner",
    slug: "forest-runner",
    localFile: "/games/sausi/racing/forest-runner/index.html",
    cats: ["racing"],
    category: "racing",
    tech: "phaser",
    tags: ["runner", "forest"],
    description: "Sprint through a forest — dodge logs and gaps.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Forest Runner.png",
  },
  {
    name: "Four Dots",
    slug: "four-dots",
    localFile: "/games/sausi/puzzle/four-dots/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["pattern", "tap"],
    description: "Tap dots in the right pattern.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Four Dots.png",
  },
  {
    name: "Fruit Basket",
    slug: "fruit-basket",
    localFile: "/games/sausi/casual/fruit-basket/index.html",
    cats: ["casual"],
    category: "casual",
    tech: "phaser",
    tags: ["catch", "fruits", "cute"],
    description: "Catch falling fruits in your basket.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Fruit Basket.png",
  },
  {
    name: "Fruit Cosmics",
    slug: "fruit-cosmics",
    localFile: "/games/sausi/casual/fruit-cosmics/index.html",
    cats: ["casual"],
    category: "casual",
    tech: "phaser",
    tags: ["fruits", "slash"],
    description: "Cosmic-themed fruit smasher.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Fruit Cosmics.png",
  },
  {
    name: "Fruit Merge",
    slug: "fruit-merge",
    localFile: "/games/sausi/casual/fruit-merge/inex.html",
    cats: ["casual"],
    category: "casual",
    tech: "html",
    tags: ["merge", "suika", "drop"],
    description: "Drop fruits — merge same kinds to evolve.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Fruit Merge.png",
  },
  {
    name: "LumaBounce",
    slug: "luma-bounce",
    localFile: "/games/sausi/arcade/luma-bounce/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["bounce", "reflex"],
    description: "Bouncy reflex arcade game.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/LumaBounce.png",
  },
  {
    name: "Glass Step",
    slug: "glass-step",
    localFile: "/games/sausi/arcade/glass-step/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["squid-game", "pick"],
    description: "Pick the safe glass tile. Don\u0027t fall.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Glass Step.png",
  },
  {
    name: "Gunman",
    slug: "gunman",
    localFile: "/games/sausi/shooter/gunman/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["western", "quickdraw"],
    description: "Quick-draw gunfight game.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Gunman.png",
  },
  {
    name: "Gun Run",
    slug: "gun-run",
    localFile: "/games/sausi/shooter/gun-run/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["run-gun", "side-scroll"],
    description: "Run-and-gun side-scroller.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Gun Run.png",
  },
  {
    name: "Hex Puzzle",
    slug: "hex-puzzle",
    localFile: "/games/sausi/puzzle/hex-puzzle/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "html",
    tags: ["hex", "blocks"],
    description: "Place hex blocks to clear the board.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Hex Puzzle.png",
  },
  {
    name: "Hungry Player",
    slug: "hungry-player",
    localFile: "/games/sausi/arcade/hungry-player/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["eat", "grow"],
    description: "Gobble food, dodge hazards, grow.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Hungry Player.png",
  },
  {
    name: "Jump Dot",
    slug: "jump-dot",
    localFile: "/games/sausi/arcade/jump-dot/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["one-button", "timing"],
    description: "Tap to jump the dot over rotating hazards.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Jump Dot.png",
  },
  {
    name: "Kaiju Krush",
    slug: "kaiju-krush",
    localFile: "/games/sausi/arcade/kaiju-krush/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["destruction", "kaiju"],
    description: "Smash through the city as a giant kaiju.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Kaiju Krush.png",
  },
  {
    name: "Laser Bounce",
    slug: "laser-bounce",
    localFile: "/games/sausi/puzzle/laser-bounce/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["lasers", "reflect", "logic"],
    description: "Reflect lasers to hit all targets.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Laser Bounce.png",
  },
  {
    name: "Link",
    slug: "link",
    localFile: "/games/sausi/puzzle/link/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["match", "mahjong"],
    description: "Link matching tiles by shortest path.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Link.png",
  },
  {
    name: "Ludo",
    slug: "ludo",
    localFile: "/games/sausi/board/ludo/index.html",
    cats: ["board"],
    category: "board",
    tech: "html",
    tags: ["dice", "classic", "family"],
    description: "Classic Ludo — you vs 3 AI opponents.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Ludo.png",
  },
  {
    name: "Mario-Like",
    slug: "mario",
    localFile: "/games/sausi/platformer/mario/index.html",
    cats: ["platformer"],
    category: "platformer",
    tech: "phaser",
    tags: ["platformer", "retro"],
    description: "Side-scrolling platformer adventure.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Mario-Like.png",
  },
  {
    name: "Math Quest",
    slug: "math-quest",
    localFile: "/games/sausi/word-quiz/math-quest/index.html",
    cats: ["word-quiz"],
    category: "word-quiz",
    tech: "phaser",
    tags: ["math", "education", "quick"],
    description: "Speed math challenge.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Math Quest.png",
  },
  {
    name: "Memory",
    slug: "memory",
    localFile: "/games/sausi/puzzle/memory/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["memory", "cards", "classic"],
    description: "Flip cards. Find pairs.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Memory.png",
  },
  {
    name: "Memory Cards",
    slug: "memory-cards",
    localFile: "/games/sausi/puzzle/memory-cards/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["memory", "cards"],
    description: "Card-matching memory test.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Memory Cards.png",
  },
  {
    name: "Number Merge",
    slug: "number-merge",
    localFile: "/games/sausi/puzzle/number-merge/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["merge", "numbers"],
    description: "Merge same numbers, climb the score.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Number Merge.png",
  },
  {
    name: "One Car",
    slug: "one-car",
    localFile: "/games/sausi/racing/one-car/index.html",
    cats: ["racing"],
    category: "racing",
    tech: "phaser",
    tags: ["traffic", "reflex"],
    description: "Steer one car through dense traffic.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/One Car.png",
  },
  {
    name: "Orbital Outpost",
    slug: "orbital-outpost",
    localFile: "/games/sausi/3d/orbital-outpost/index.html",
    cats: ["3d"],
    category: "3d",
    tech: "phaser",
    tags: ["3d", "space", "defense"],
    description: "3D space-station defense.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Orbital Outpost.png",
  },
  {
    name: "Pac-Man",
    slug: "pacman",
    localFile: "/games/sausi/arcade/pacman/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["maze", "classic"],
    description: "Eat dots. Avoid ghosts.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Pac-Man.png",
  },
  {
    name: "Pairing",
    slug: "pairing",
    localFile: "/games/sausi/puzzle/pairing/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["match", "quick"],
    description: "Pair up matching items quickly.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Pairing.png",
  },
  {
    name: "Parkour",
    slug: "parkour",
    localFile: "/games/sausi/platformer/parkour/index.html",
    cats: ["platformer"],
    category: "platformer",
    tech: "phaser",
    tags: ["parkour", "run"],
    description: "Wall-run, slide, and vault forward.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Parkour.png",
  },
  {
    name: "Pathfinder",
    slug: "pathfinder",
    localFile: "/games/sausi/puzzle/pathfinder/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["maze", "path"],
    description: "Solve maze paths under time pressure.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Pathfinder.png",
  },
  {
    name: "Perfect Square",
    slug: "perfect-square",
    localFile: "/games/sausi/puzzle/perfect-square/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["timing", "precision"],
    description: "Tap when the square aligns perfectly.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Perfect Square.png",
  },
  {
    name: "Pirates",
    slug: "pirates",
    localFile: "/games/sausi/arcade/pirates/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["pirates", "ships"],
    description: "Sail and battle on the high seas.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Pirates.png",
  },
  {
    name: "Planet Visitor",
    slug: "planet-visitor",
    localFile: "/games/sausi/3d/planet-visitor/index.html",
    cats: ["3d"],
    category: "3d",
    tech: "phaser",
    tags: ["3d", "space", "explore"],
    description: "Land on alien planets in 3D.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Planet Visitor.png",
  },
  {
    name: "Planet War",
    slug: "planet-war",
    localFile: "/games/sausi/3d/planet-war/index.html",
    cats: ["3d"],
    category: "3d",
    tech: "phaser",
    tags: ["3d", "space", "defense"],
    description: "Defend your planet from cosmic invaders.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Planet War.png",
  },
  {
    name: "Projectile Enemy",
    slug: "projectile-enemy",
    localFile: "/games/sausi/shooter/projectile-enemy/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["bullet-hell", "reflex"],
    description: "Dodge and counter ranged enemies.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Projectile Enemy.png",
  },
  {
    name: "Quiz",
    slug: "quiz",
    localFile: "/games/sausi/word-quiz/quiz/index.html",
    cats: ["word-quiz"],
    category: "word-quiz",
    tech: "phaser",
    tags: ["trivia", "education"],
    description: "Test your knowledge across categories.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Quiz.png",
  },
  {
    name: "Red Light, Green Light",
    slug: "red-light-green-light",
    localFile: "/games/sausi/arcade/red-light-green-light/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["squid-game", "reflex"],
    description: "Move on green. Freeze on red.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Red Light, Green Light.png",
  },
  {
    name: "Road Cross",
    slug: "road-cross",
    localFile: "/games/sausi/arcade/road-cross/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["frogger", "timing"],
    description: "Cross busy roads safely.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Road Cross.png",
  },
  {
    name: "Road Fighter",
    slug: "road-fighter",
    localFile: "/games/sausi/racing/road-fighter/index.html",
    cats: ["racing"],
    category: "racing",
    tech: "phaser",
    tags: ["traffic", "race", "retro"],
    description: "Top-down race weaving through traffic.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Road Fighter.png",
  },
  {
    name: "Robot Destruction",
    slug: "robot-destruction",
    localFile: "/games/sausi/shooter/robot-destruction/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["robots", "blaster"],
    description: "Blast incoming robots to scrap.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Robot Destruction.png",
  },
  {
    name: "Screw Master",
    slug: "screw-master",
    localFile: "/games/sausi/puzzle/screw-master/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["sort", "mechanical"],
    description: "Unscrew and sort the metal pieces.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Screw Master.png",
  },
  {
    name: "Shadow Runner",
    slug: "shadow-runner",
    localFile: "/games/sausi/racing/shadow-runner/index.html",
    cats: ["racing"],
    category: "racing",
    tech: "phaser",
    tags: ["runner", "dark"],
    description: "Sprint through a shadow world.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Shadow Runner.png",
  },
  {
    name: "Shadow Shooter",
    slug: "shadow-shooter",
    localFile: "/games/sausi/shooter/shadow-shooter/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["stealth", "shooter"],
    description: "Pick off shadow enemies from cover.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Shadow Shooter.png",
  },
  {
    name: "Shape Collector",
    slug: "shape-collector",
    localFile: "/games/sausi/arcade/shape-collector/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["shapes", "match"],
    description: "Catch only the matching shapes.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Shape Collector.png",
  },
  {
    name: "Shape Fitter",
    slug: "shape-fitter",
    localFile: "/games/sausi/puzzle/shape-fitter/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["shapes", "kids"],
    description: "Fit shapes into the right slots.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Shape Fitter.png",
  },
  {
    name: "Shoot Enemy",
    slug: "shoot-enemy",
    localFile: "/games/sausi/shooter/shoot-enemy/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["aim", "reflex"],
    description: "Pick off enemies before they reach you.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Shoot Enemy.png",
  },
  {
    name: "Shooter",
    slug: "shooter",
    localFile: "/games/sausi/shooter/shooter/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["arena", "top-down"],
    description: "Top-down arena shooter.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Shooter.png",
  },
  {
    name: "Signal Circuit",
    slug: "signal-circuit",
    localFile: "/games/sausi/puzzle/signal-circuit/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["logic", "circuit"],
    description: "Route signals through circuit gates.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Signal Circuit.png",
  },
  {
    name: "Sky High",
    slug: "sky-high",
    localFile: "/games/sausi/arcade/sky-high/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["climb", "endless"],
    description: "Climb endlessly into the sky.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Sky High.png",
  },
  {
    name: "Slide Puzzle",
    slug: "slide-puzzle",
    localFile: "/games/sausi/puzzle/slide-puzzle/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["sliding", "classic"],
    description: "Reassemble the image by sliding tiles.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Slide Puzzle.png",
  },
  {
    name: "Snake",
    slug: "snake",
    localFile: "/games/sausi/arcade/snake/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["snake", "classic"],
    description: "Eat. Grow. Don\u0027t hit yourself.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Snake.png",
  },
  {
    name: "Snake \u0026 Ladder",
    slug: "snake-and-ladder",
    localFile: "/games/sausi/board/snake-and-ladder/index.html",
    cats: ["board"],
    category: "board",
    tech: "phaser",
    tags: ["dice", "family", "classic"],
    description: "Roll the dice. Climb. Slide. Win.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Snake & Ladder.png",
  },
  {
    name: "Sniper",
    slug: "sniper",
    localFile: "/games/sausi/shooter/sniper/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["scope", "precision"],
    description: "Steady your scope. One shot, one kill.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Sniper.png",
  },
  {
    name: "Space Fighter",
    slug: "space-fighter",
    localFile: "/games/sausi/shooter/space-fighter/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["space", "dogfight"],
    description: "Dogfight through asteroid fields.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Space Fighter.png",
  },
  {
    name: "Spaceman",
    slug: "spaceman",
    localFile: "/games/sausi/arcade/spaceman/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["space", "float"],
    description: "Float and survive in zero gravity.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Spaceman.png",
  },
  {
    name: "Space Waves",
    slug: "space-waves",
    localFile: "/games/sausi/arcade/space-waves/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["space", "wave"],
    description: "Surf waves of space debris.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Space Waves.png",
  },
  {
    name: "Square One",
    slug: "square-one",
    localFile: "/games/sausi/puzzle/square-one/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["sliding", "minimal"],
    description: "Slide squares to clear the board.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Square One.png",
  },
  {
    name: "Stack Tower",
    slug: "stack-tower",
    localFile: "/games/sausi/3d/stack-tower/index.html",
    cats: ["3d"],
    category: "3d",
    tech: "three",
    tags: ["3d", "stack", "timing"],
    description: "Stack 3D blocks for the highest tower.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Stack Tower.png",
  },
  {
    name: "Stick Game",
    slug: "stick-game",
    localFile: "/games/sausi/arcade/stick-game/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["stick", "draw"],
    description: "Draw sticks to bridge gaps.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Stick Game.png",
  },
  {
    name: "Stick Toss",
    slug: "stick-toss",
    localFile: "/games/sausi/arcade/stick-toss/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["aim", "spin"],
    description: "Toss sticks at the spinning target.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Stick Toss.png",
  },
  {
    name: "Straight Rush",
    slug: "straight-rush",
    localFile: "/games/sausi/racing/straight-rush/index.html",
    cats: ["racing"],
    category: "racing",
    tech: "phaser",
    tags: ["sprint", "reflex"],
    description: "Sprint forward — react to oncoming hazards.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Straight Rush.png",
  },
  {
    name: "Survival Run",
    slug: "survival-run",
    localFile: "/games/sausi/racing/survival-run/index.html",
    cats: ["racing"],
    category: "racing",
    tech: "phaser",
    tags: ["survival", "runner"],
    description: "Outrun the danger as long as you can.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Survival Run.png",
  },
  {
    name: "Survivor",
    slug: "survivor",
    localFile: "/games/sausi/shooter/survivor/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["horde", "survival", "auto"],
    description: "Vampire-survivors-style horde survival.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Survivor.png",
  },
  {
    name: "Table Tennis",
    slug: "table-tennis",
    localFile: "/games/sausi/sports/table-tennis/index.html",
    cats: ["sports"],
    category: "sports",
    tech: "phaser",
    tags: ["pong", "sport"],
    description: "Volley the ping-pong ball.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Table Tennis.png",
  },
  {
    name: "Tap Target",
    slug: "tap-target",
    localFile: "/games/sausi/arcade/tap-target/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["tap", "reflex"],
    description: "Tap targets before they vanish.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Tap Target.png",
  },
  {
    name: "Tee Shooter",
    slug: "tee-shooter",
    localFile: "/games/sausi/shooter/tee-shooter/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["aim", "tee"],
    description: "Tee-up trick-shot shooter.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Tee Shooter.png",
  },
  {
    name: "Tetris",
    slug: "tetris",
    localFile: "/games/sausi/puzzle/tetris/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "html",
    tags: ["blocks", "classic"],
    description: "The classic falling-block puzzle.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Tetris.png",
  },
  {
    name: "That Level Again — 1",
    slug: "that-level-again-1",
    localFile: "/games/sausi/platformer/that-level-again-1/index.html",
    cats: ["platformer"],
    category: "platformer",
    tech: "phaser",
    tags: ["trick", "platformer"],
    description: "Trick-platformer level 1.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/That Level Again — 1.png",
  },
  {
    name: "That Level Again — 2",
    slug: "that-level-again-2",
    localFile: "/games/sausi/platformer/that-level-again-2/index.html",
    cats: ["platformer"],
    category: "platformer",
    tech: "phaser",
    tags: ["trick", "platformer"],
    description: "Trick-platformer level 2.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/That Level Again — 1.png",
  },
  {
    name: "That Level Again — 3",
    slug: "that-level-again-3",
    localFile: "/games/sausi/platformer/that-level-again-3/index.html",
    cats: ["platformer"],
    category: "platformer",
    tech: "phaser",
    tags: ["trick", "platformer"],
    description: "Trick-platformer level 3.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/That Level Again — 1.png",
  },
  {
    name: "That Level Again — 4",
    slug: "that-level-again-4",
    localFile: "/games/sausi/platformer/that-level-again-4/index.html",
    cats: ["platformer"],
    category: "platformer",
    tech: "phaser",
    tags: ["trick", "platformer"],
    description: "Trick-platformer level 4.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/That Level Again — 1.png",
  },
  {
    name: "That Level Again — 5",
    slug: "that-level-again-5",
    localFile: "/games/sausi/platformer/that-level-again-5/index.html",
    cats: ["platformer"],
    category: "platformer",
    tech: "phaser",
    tags: ["trick", "platformer"],
    description: "Trick-platformer level 5.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/That Level Again — 1.png",
  },
  {
    name: "Thunder God",
    slug: "thunder-god",
    localFile: "/games/sausi/shooter/thunder-god/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["thunder", "power"],
    description: "Smite enemies with lightning.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Thunder God.png",
  },
  {
    name: "Tic-Tac-Toe",
    slug: "tic-tac-toe",
    localFile: "/games/sausi/board/tic-tac-toe/index.html",
    cats: ["board"],
    category: "board",
    tech: "phaser",
    tags: ["classic", "quick"],
    description: "X\u0027s and O\u0027s. Three in a row wins.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Tic-Tac-Toe.png",
  },
  {
    name: "Tile Tap",
    slug: "tile-tap",
    localFile: "/games/sausi/puzzle/tile-tap/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["tap", "tile", "classic"],
    description: "Tap only the dark tiles. Don\u0027t miss.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Tile Tap.png",
  },
  {
    name: "Tower Shooter",
    slug: "tower-shooter",
    localFile: "/games/sausi/shooter/tower-shooter/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["defense", "tower"],
    description: "Defend your tower from waves of enemies.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Tower Shooter.png",
  },
  {
    name: "Trench Defence",
    slug: "trench-defence",
    localFile: "/games/sausi/shooter/trench-defence/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["defense", "war"],
    description: "Hold the trench against the assault.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Trench Defence.png",
  },
  {
    name: "Two Cars",
    slug: "two-cars",
    localFile: "/games/sausi/racing/two-cars/index.html",
    cats: ["racing"],
    category: "racing",
    tech: "phaser",
    tags: ["dual", "reflex"],
    description: "Steer two cars at once. Catch \u0026 dodge.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Two Cars.png",
  },
  {
    name: "Two Cars AI",
    slug: "two-cars-ai",
    localFile: "/games/sausi/racing/two-cars-ai/index.html",
    cats: ["racing"],
    category: "racing",
    tech: "phaser",
    tags: ["dual", "ai"],
    description: "AI-twist on the two-cars classic.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Two Cars AI.png",
  },
  {
    name: "Unruly",
    slug: "unruly",
    localFile: "/games/sausi/puzzle/unruly/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "phaser",
    tags: ["logic", "binary"],
    description: "Place tiles by no-three-in-a-row rules.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Unruly.png",
  },
  {
    name: "Vaccine Shooter",
    slug: "vaccine-shooter",
    localFile: "/games/sausi/shooter/vaccine-shooter/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["health", "shooter"],
    description: "Shoot viruses with your vaccine gun.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Vaccine Shooter.png",
  },
  {
    name: "Whack-a-Bug",
    slug: "whack-a-bug",
    localFile: "/games/sausi/arcade/whack-a-bug/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "phaser",
    tags: ["whack", "reflex"],
    description: "Bonk the bugs as they pop up.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Whack-a-Bug.png",
  },
  {
    name: "Wordlee",
    slug: "wordle",
    localFile: "/games/sausi/word-quiz/wordle/index.html",
    cats: ["word-quiz"],
    category: "word-quiz",
    tech: "phaser",
    tags: ["wordle", "letters"],
    description: "Guess the 5-letter word in 6 tries.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Wordlee.png",
  },
  {
    name: "Words of Wonder",
    slug: "words-of-wonder",
    localFile: "/games/sausi/word-quiz/words-of-wonder/index.html",
    cats: ["word-quiz"],
    category: "word-quiz",
    tech: "phaser",
    tags: ["letters", "spelling"],
    description: "Build words from a wheel of letters.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Words of Wonder.png",
  },
  {
    name: "Penalty Shootout",
    slug: "penalty",
    localFile: "/games/sausi/sports/penalty/index.html",
    cats: ["sports"],
    category: "sports",
    tech: "phaser",
    tags: ["soccer", "quick"],
    description: "One-on-one penalty kicks vs the keeper.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Penalty Shootout.png",
  },
  {
    name: "Swipe Assassin",
    slug: "swipe-assassin",
    localFile: "/games/sausi/arcade/swipe-assassin/index.html",
    cats: ["arcade"],
    category: "arcade",
    tech: "html",
    tags: ["swipe", "slash"],
    description: "Swipe to slice incoming threats.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Swipe Assassin.png",
  },
  {
    name: "Level Devil",
    slug: "level-devil",
    localFile: "/games/sausi/platformer/level-devil/index.html",
    cats: ["platformer"],
    category: "platformer",
    tech: "three",
    tags: ["trick", "platformer"],
    description: "Trickster platformer that hates you.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Level Devil.png",
  },
  {
    name: "Line Trap",
    slug: "line-trap",
    localFile: "/games/sausi/puzzle/line-trap/index.html",
    cats: ["puzzle"],
    category: "puzzle",
    tech: "html",
    tags: ["draw", "minimal"],
    description: "Trap the dot inside your line.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Line Trap.png",
  },
  {
    name: "Window Shooter",
    slug: "window-shooter",
    localFile: "/games/sausi/shooter/window-shooter/index.html",
    cats: ["shooter"],
    category: "shooter",
    tech: "phaser",
    tags: ["aim", "reflex"],
    description: "Pick off enemies through the window.",
    license: "MIT",
    source: "https://github.com/sausi-7/games",
    poster: "/game-posters/Game-Images/Window Shooter.png",
  },
];

export const gameCategories = [
  {
    id: "puzzle",
    label: "Puzzle",
    color: "#7c3aed",
    desc: "Logic, matching, and brain games",
  },
  {
    id: "arcade",
    label: "Arcade",
    color: "#ec4899",
    desc: "Fast classic-style action",
  },
  {
    id: "shooter",
    label: "Shooter",
    color: "#ef4444",
    desc: "Aim, defend, and survive",
  },
  {
    id: "racing",
    label: "Racing",
    color: "#f59e0b",
    desc: "Cars, runners, and speed",
  },
  {
    id: "sports",
    label: "Sports",
    color: "#10b981",
    desc: "Skill-based sports challenges",
  },
  {
    id: "platformer",
    label: "Platformer",
    color: "#06b6d4",
    desc: "Jump, run, and explore",
  },
  {
    id: "casual",
    label: "Casual",
    color: "#f472b6",
    desc: "Relaxed pick-up-and-play games",
  },
  {
    id: "board",
    label: "Board",
    color: "#64748b",
    desc: "Classic tabletop games",
  },
  {
    id: "word-quiz",
    label: "Word \u0026 Quiz",
    color: "#3b82f6",
    desc: "Words, maths, and trivia",
  },
  {
    id: "3d",
    label: "3D",
    color: "#8b5cf6",
    desc: "Immersive three-dimensional games",
  },
];
